Add HIP equivalent codes and associated dependencies

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,10 +9,16 @@
 
 configure=$0
 build_top=$PWD
+root_dir=$(dirname "$(readlink -f "$0")")
+external_dir=$root_dir/external/HIP
 
 cuda_path=
 cuda_check=include/cuda.h
 enable_cuda=
+
+hip_path=
+hip_check=include/hip/hip_runtime_api.h
+enable_hip=yes
 
 enable_python=
 
@@ -23,12 +29,12 @@ have_nccl=no
 nccl_path=
 nccl_check=include/nccl.h
 
-# CNTK Custom MKL Version
-cntk_custom_mkl_version=3
+# MKLML Version
+mklml_version=mklml_lnx_2018.0.1.20171007
 
 have_mkl=no
 mkl_path=
-mkl_check=$cntk_custom_mkl_version/include/mkl.h
+mkl_check=include/mkl_version.h
 
 # Experimental OpenBLAS support.
 have_openblas=no
@@ -72,9 +78,17 @@ have_cub=no
 cub_path=
 cub_check=cub/cub.cuh
 
+have_cubhip=no
+cubhip_path=
+cubhip_check=cub/cub.cuh
+
 have_cudnn=no
 cudnn_path=
 cudnn_check=cuda/include/cudnn.h
+
+have_hipdnn=no
+hipdnn_path=
+hipdnn_check=include/hipDNN.h
 
 have_opencv=no
 opencv_path=
@@ -111,21 +125,24 @@ default_use_asgd=yes
 enable_asgd=$default_use_asgd
 
 # List from best to worst choice
-default_path_list="/usr /usr/local /opt /opt/local /lib /usr/lib"
+default_path_list="/usr /usr/local /opt /opt/rocm /opt/local /lib /usr/lib"
 
 # List from best to worst choice
-default_mkls="CNTKCustomMKL"
+default_mkls="mklml/$mklml_version"
 default_openblas=""
 
 default_boost="boost-1.60.0"
 
 default_cudas="cuda-8.0 cuda-7.5"
+default_hip="hip"
 default_nccls="nccl"
 default_kaldis="kaldi-trunk kaldi-c024e8aa"
 default_gdk_includes="include/nvidia/gdk"
 default_gdk_nvml_libs="src/gdk/nvml/lib"
 default_cubs="cub-1.4.1"
+default_cubhips="cub-hip"
 default_cudnns="cudnn-6.0 cudnn-5.1 cudnn-5.0"
+default_hipdnn="hipDNN"
 default_opencvs="opencv-3.1.0 opencv-3.0.0"
 default_protobuf="protobuf-3.1.0"
 default_libzips="libzip-1.1.2"
@@ -134,7 +151,7 @@ default_mpi="mpi"
 
 function default_paths ()
 {
-    echo $build_top $HOME $default_path_list
+    echo $build_top $external_dir $default_path_list $HOME
 }
 
 # $1 is directory
@@ -198,6 +215,11 @@ function find_cuda ()
     find_dir "$default_cudas" "$cuda_check"
 }
 
+function find_hip ()
+{
+    find_dir "$default_hip" "$hip_check"
+}
+
 function find_kaldi ()
 {
     find_dir "$default_kaldis" "$kaldi_check"
@@ -218,9 +240,19 @@ function find_cub ()
     find_dir "$default_cubs" "$cub_check"
 }
 
+function find_cubhip ()
+{
+	find_dir "$default_cubhips" "$cubhip_check"
+}
+
 function find_cudnn ()
 {
     find_dir "$default_cudnns" "$cudnn_check"
+}
+
+function find_hipdnn ()
+{
+    find_dir "$default_hipdnn" "$hipdnn_check"
 }
 
 function find_opencv ()
@@ -268,6 +300,17 @@ function default_use_cuda ()
     fi
 }
 enable_cuda=$(default_use_cuda)
+
+function default_use_hip ()
+{
+    if test x$(find_hip) = x || test x$(find_hipdnn) = x || test x$(find_cubhip) = x
+    then
+        echo no
+    else
+        echo yes
+    fi
+}
+#enable_hip=$(default_use_hip)
 
 # TODO allow to pick up from path?
 function check_swig ()
@@ -366,16 +409,19 @@ function show_help ()
     echo "  --1bitsgd[=(yes|no)] use 1Bit SGD $(show_default ${default_use_1bitsgd})"
     echo "  --asgd[=(yes|no)] use ASGD powered by Multiverso $(show_default $(default_use_asgd))"
     echo "  --cuda[=(yes|no)] use cuda GPU $(show_default $(default_use_cuda))"
+    echo "  --hip[=(yes|no)] use HIP $(show_default $(default_use_hip))" #MCW
     echo "  --python[=(yes|no)] with Python bindings $(show_default $(default_use_python))"
     echo "  --java[=(yes|no)] with Java bindings $(show_default $(default_use_java))"
     echo "  --with-jdk[=directory] $(show_default $(find_jdk))"
     echo "  --mpi[=(yes|no)] use MPI communication $(show_default ${default_use_mpi})"
     echo "  --gdr[=(yes|no)] use GPUDirect RDMA $(show_default ${default_cuda_gdr})"
     echo "  --with-cuda[=directory] $(show_default $(find_cuda))"
+    echo "  --with-hip[=directory] $(show_default $(find_hip))"
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
     echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
     echo "  --with-cudnn[=directory] $(show_default $(find_cudnn))"
+    echo "  --with-hipdnn[=directory] $(show_default $(find_hipdnn))"
     echo "  --with-nccl[=directory] $(show_default $(find_nccl))"
     echo "  --with-mkl[=directory] $(show_default $(find_mkl))"
     echo "  --with-mkl-sequential[=directory] $(show_default $(find_mkl))"
@@ -410,7 +456,7 @@ do
         *=)   optarg= ;;
         *)    optarg= ;;
     esac
-
+    #echo "optarg is : $optarg"
     case $key in
         -h|--help)
             show_help
@@ -469,6 +515,17 @@ do
                 enable_cuda=$optarg
             else
                 echo "Invalid value for --cuda $optarg"
+                show_help
+                exit
+            fi
+            ;;
+
+	--hip*)
+            if test x$optarg = xyes || test x$optarg = xno
+            then
+                enable_hip=$optarg
+            else
+                echo "Invalid value for --hip $optarg"
                 show_help
                 exit
             fi
@@ -630,8 +687,30 @@ do
             fi
             ;;
 
+        --with-hip*)
+            enable_hip=yes
+            if test x$optarg = x
+            then
+                hip_path=$(find_hip)
+                if test x$hip_path = x
+                then
+                    echo "Cannot find HIP directory."
+                    echo "Please specify a value for --with-hip"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $hip_check) = yes
+                then
+                    hip_path=$optarg
+                else
+                    echo "Invalid hip directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
         --with-cub*)
-            have_cub=yes
+	    have_cub=yes
             if test x$optarg = x
             then
                 cub_path=$(find_cub)
@@ -652,6 +731,36 @@ do
                 fi
             fi
             ;;
+
+	--with-cubhip*)
+	    if $(enable_hip) = no
+	    then
+		echo "CUB-HIP specified without enabling HIP compile."
+		echo "Enabel HIP compile with --hip=yes before specifying CUB-HIP"
+		exit 
+	    fi
+            have_cubhip=yes
+            if test x$optarg = x
+            then
+                cubhip_path=$(find_cub)
+                if test x$cub_path = x
+                then
+                    echo "Cannot find CUB-HIP directory."
+                    echo "Please specify a value for --with-cub"
+                    echo "CUB-HIP can be downloaded from https://github.com/ROCmSoftwarePlatform/cub-hip, extract the archive to /usr/local"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $cubhip_check) = yes
+                then
+                    cubhip_path=$optarg
+                else
+                    echo "Invalid CUB-HIP directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
         --with-gdk-include*)
             have_gdk_include=yes
             if test x$optarg = x
@@ -715,6 +824,33 @@ do
                 fi
             fi
             ;;
+	--with-hipdnn*)
+	    if $(enable_hip) = no
+            then
+                echo "CUB-HIP specified without enabling HIP compile."
+                echo "Enabel HIP compile with --hip=yes before specifying CUB-HIP"
+                exit
+            fi
+            have_hipdnn=yes
+            if test x$optarg = x
+            then
+                hipdnn_path=$(find_hipdnn)
+                if test x$hipdnn_path = x
+                then
+                    echo "Cannot find hipDNN directory."
+                    echo "Please specify a value for --with-hipdnn"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $hipdnn_check) = yes
+                then
+                    hipdnn_path=$optarg
+                else
+                    echo "Invalid hipDNN directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
         --with-nccl*)
             have_nccl=yes
             if test x$optarg = x
@@ -740,16 +876,12 @@ do
         --with-mkl*)
             have_mkl=yes
             mathlib=mkl
-            mkl_threading=parallel
-            case $key in
-                --with-mkl-sequential*) mkl_threading=sequential ;;
-            esac
             if test x$optarg = x
             then
                 mkl_path=$(find_mkl)
                 if test x$mkl_path = x
                 then
-                    echo "Cannot find CNTK custom MKL directory (version $cntk_custom_mkl_version)"
+                    echo "Cannot find MKLML directory (version $mklml_version)"
                     echo "Please specify a value for --with-mkl"
                     exit 1
                 fi
@@ -758,7 +890,7 @@ do
                 then
                     mkl_path=$optarg
                 else
-                    echo "Invalid CNTK custom MKL directory $optarg"
+                    echo "Invalid MKLML directory $optarg"
                     exit 1
                 fi
             fi
@@ -942,7 +1074,7 @@ then
     if test x$mkl_path = x
     then
         echo "Cannot find a CPU math library."
-        echo "Please specify --with-mkl, --with-mkl-sequential, --with-openblas with a path."
+        echo "Please specify --with-mkl, --with-openblas with a path."
         exit 1
     else
         mathlib=mkl
@@ -959,6 +1091,19 @@ then
         enable_cuda=no
     else
         echo Found cuda at $cuda_path
+    fi
+fi
+
+if test x$enable_hip = xyes && test x$hip_path = x
+then
+    /bin/bash $root_dir/install_hiplibs.sh
+    hip_path=$(find_hip)
+    if test x$hip_path = x ; then
+        echo Cannot locate a HIP directory
+        echo GPU will be disabled
+        enable_hip=no
+    else
+        echo Found HIP at $hip_path
     fi
 fi
 
@@ -986,7 +1131,7 @@ then
     fi
 fi
 
-if test $enable_cuda = yes && test x$cub_path = x
+if test $enable_cuda = yes && test x$cub_path = x && test $enable_hip = no
 then
     cub_path=$(find_cub)
     if test x$cub_path = x ; then
@@ -999,6 +1144,19 @@ then
     fi
 fi
 
+if test $enable_hip = yes && test x$cubhip_path = x
+then
+    cubhip_path=$(find_cubhip)
+    if test x$cubhip_path = x ; then
+        echo Cannot locate CUB-HIP directory
+        echo GPU will be disabled
+        echo CUB-HIP can be downloaded from https://github.com/ROCmSoftwarePlatform/cub-hip, extract the archive to /usr/local 
+        enable_hip=no
+    else
+        echo Found CUB-HIP at $cubhip_path
+    fi
+fi
+
 if test $enable_cuda = yes && test x$cudnn_path = x
 then
     cudnn_path=$(find_cudnn)
@@ -1007,6 +1165,17 @@ then
         echo CNTK will use default convolution engine.
     else
         echo Found cuDNN at $cudnn_path
+    fi
+fi
+
+if test $enable_hip = yes && test x$hipdnn_path = x
+then
+    hipdnn_path=$(find_hipdnn)
+    if test x$hipdnn_path = x ; then
+        echo Cannot locate hipDNN directory
+        echo CNTK will use default convolution engine.
+    else
+        echo Found hipDNN at $hipdnn_path
     fi
 fi
 
@@ -1147,7 +1316,6 @@ case $mathlib in
     mkl)
         echo MKL_PATH=$mkl_path >> $config
         echo MKL_THREADING=$mkl_threading >> $config
-        echo CNTK_CUSTOM_MKL_VERSION=$cntk_custom_mkl_version >> $config
         ;;
     openblas)
         echo OPENBLAS_PATH=$openblas_path >> $config
@@ -1163,12 +1331,23 @@ if test $cuda_gdr = yes ; then
 else
     echo CUDA_GDR=0 >> $config
 fi
-if test $enable_cuda = yes ; then
-    echo CUDA_PATH=$cuda_path >> $config
-    echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
-    echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
-    echo CUB_PATH=$cub_path >> $config
-    echo CUDNN_PATH=$cudnn_path >> $config
+if test $enable_cuda = yes || test $enable_hip = yes ; then
+    if test $enable_cuda = yes
+    then
+    	echo CUDA_PATH=$cuda_path >> $config
+    	echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
+    	echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
+        echo CUDNN_PATH=$cudnn_path >> $config
+    fi
+    if test $enable_hip = no
+    then
+	echo CUB_PATH=$cub_path >> $config
+    else
+        echo HIP_PATH=$hip_path >> $config
+	echo CUB_PATH=$cubhip_path >> $config
+        echo HIPDNN_PATH=$hipdnn_path >> $config
+        echo EXTERNAL_DIR=$external_dir >> $config
+    fi
     [ -z "$nccl_path" ] || echo NCCL_PATH=$nccl_path >> $config
 fi
 if test $enable_python = yes || test $enable_java = yes ; then
