hippify cntk on nv platform
- hippified cntk
- unsupports asgd as of now
- untested build

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,6 +14,10 @@ cuda_path=
 cuda_check=include/cuda.h
 enable_cuda=
 
+hip_path=
+hip_check=include/hip/hip_runtime_api.h
+enable_hip=
+
 enable_python=
 
 enable_java=
@@ -69,7 +73,7 @@ gdk_nvml_lib_path=
 gdk_nvml_lib_check=libnvidia-ml.so
 
 have_cub=no
-cub_path=
+cub_path=/usr/local/cub-hip/
 cub_check=cub/cub.cuh
 
 have_cudnn=no
@@ -77,7 +81,7 @@ cudnn_path=
 cudnn_check=cuda/include/cudnn.h
 
 have_opencv=no
-opencv_path=
+opencv_path=/usr/local/opencv-3.1.0
 opencv_check=include/opencv2/opencv.hpp
 
 have_libzip=no
@@ -111,7 +115,7 @@ default_use_asgd=yes
 enable_asgd=$default_use_asgd
 
 # List from best to worst choice
-default_path_list="/usr /usr/local /opt /opt/local /lib /usr/lib"
+default_path_list="/usr /usr/local /opt /opt/rocm /opt/local /lib /usr/lib"
 
 # List from best to worst choice
 default_mkls="CNTKCustomMKL"
@@ -120,6 +124,7 @@ default_openblas=""
 default_boost="boost-1.60.0"
 
 default_cudas="cuda-8.0 cuda-7.5"
+default_hip="hip"
 default_nccls="nccl"
 default_kaldis="kaldi-trunk kaldi-c024e8aa"
 default_gdk_includes="include/nvidia/gdk"
@@ -198,6 +203,11 @@ function find_cuda ()
     find_dir "$default_cudas" "$cuda_check"
 }
 
+function find_hip ()
+{
+    find_dir "$default_hip" "$hip_check"
+}
+
 function find_kaldi ()
 {
     find_dir "$default_kaldis" "$kaldi_check"
@@ -268,6 +278,7 @@ function default_use_cuda ()
     fi
 }
 enable_cuda=$(default_use_cuda)
+enable_hip=yes
 
 # TODO allow to pick up from path?
 function check_swig ()
@@ -366,12 +377,14 @@ function show_help ()
     echo "  --1bitsgd[=(yes|no)] use 1Bit SGD $(show_default ${default_use_1bitsgd})"
     echo "  --asgd[=(yes|no)] use ASGD powered by Multiverso $(show_default $(default_use_asgd))"
     echo "  --cuda[=(yes|no)] use cuda GPU $(show_default $(default_use_cuda))"
+    echo "  --hip[=(yes|no)] use HIP $(show_default $(default_use_cuda))" #MCW
     echo "  --python[=(yes|no)] with Python bindings $(show_default $(default_use_python))"
     echo "  --java[=(yes|no)] with Java bindings $(show_default $(default_use_java))"
     echo "  --with-jdk[=directory] $(show_default $(find_jdk))"
     echo "  --mpi[=(yes|no)] use MPI communication $(show_default ${default_use_mpi})"
     echo "  --gdr[=(yes|no)] use GPUDirect RDMA $(show_default ${default_cuda_gdr})"
     echo "  --with-cuda[=directory] $(show_default $(find_cuda))"
+    echo "  --with-hip[=directory] $(show_default $(find_hip))"
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
     echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
@@ -410,7 +423,7 @@ do
         *=)   optarg= ;;
         *)    optarg= ;;
     esac
-
+    #echo "optarg is : $optarg"
     case $key in
         -h|--help)
             show_help
@@ -469,6 +482,17 @@ do
                 enable_cuda=$optarg
             else
                 echo "Invalid value for --cuda $optarg"
+                show_help
+                exit
+            fi
+            ;;
+
+	--hip*)
+            if test x$optarg = xyes || test x$optarg = xno
+            then
+                enable_hip=$optarg
+            else
+                echo "Invalid value for --hip $optarg"
                 show_help
                 exit
             fi
@@ -629,6 +653,29 @@ do
                 fi
             fi
             ;;
+
+	--with-hip*)
+            enable_hip=yes
+            if test x$optarg = x
+            then
+                hip_path=$(find_cuda)
+                if test x$hip_path = x
+                then
+                    echo "Cannot find HIP directory."
+                    echo "Please specify a value for --with-hip"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $hip_check) = yes
+                then
+                    hip_path=$optarg
+                else
+                    echo "Invalid hip directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
 
         --with-cub*)
             have_cub=yes
@@ -962,6 +1009,18 @@ then
     fi
 fi
 
+if test x$enable_hip = xyes && test x$hip_path = x
+then
+    hip_path=$(find_hip)
+    if test x$hip_path = x ; then
+        echo Cannot locate a HIP directory
+        echo GPU will be disabled
+        enable_hip=no
+    else
+        echo Found HIP at $hip_path
+    fi
+fi
+
 if test $enable_cuda = yes && test x$gdk_include_path = x
 then
     gdk_include_path=$(find_gdk_include)
@@ -1163,8 +1222,9 @@ if test $cuda_gdr = yes ; then
 else
     echo CUDA_GDR=0 >> $config
 fi
-if test $enable_cuda = yes ; then
+if test $enable_cuda = yes || test $enable_hip = yes ; then
     echo CUDA_PATH=$cuda_path >> $config
+    echo HIP_PATH=$hip_path >> $config
     echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
     echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
     echo CUB_PATH=$cub_path >> $config
