hip libs integration on NV
- hipdnn integration
- hipsparse integration
- builadable on NV platform

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -76,9 +76,13 @@ have_cub=no
 cub_path=/usr/local/cub-hip/
 cub_check=cub/cub.cuh
 
+have_cudnn=no
+cudnn_path=/usr/local/cudnn-6.0/
+cudnn_check=cuda/include/cudnn.h
+
 have_hipdnn=no
-hipdnn_path=
-hipdnn_check=cuda/include/hipDNN.h
+hipdnn_path=/opt/rocm/hipdnn/
+hipdnn_check=include/hipDNN.h
 
 have_opencv=no
 opencv_path=/usr/local/opencv-3.1.0
@@ -130,7 +134,8 @@ default_kaldis="kaldi-trunk kaldi-c024e8aa"
 default_gdk_includes="include/nvidia/gdk"
 default_gdk_nvml_libs="src/gdk/nvml/lib"
 default_cubs="cub-1.4.1"
-default_hipdnns="hipdnn-6.0 hipdnn-5.1 hipdnn-5.0"
+default_cudnns="cudnn-6.0 cudnn-5.1 cudnn-5.0"
+default_hipdnn="hipdnn"
 default_opencvs="opencv-3.1.0 opencv-3.0.0"
 default_protobuf="protobuf-3.1.0"
 default_libzips="libzip-1.1.2"
@@ -228,9 +233,14 @@ function find_cub ()
     find_dir "$default_cubs" "$cub_check"
 }
 
+function find_cudnn ()
+{
+    find_dir "$default_cudnns" "$cudnn_check"
+}
+
 function find_hipdnn ()
 {
-    find_dir "$default_hipdnns" "$hipdnn_check"
+    find_dir "$default_hipdnn" "$hipdnn_check"
 }
 
 function find_opencv ()
@@ -388,6 +398,7 @@ function show_help ()
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
     echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
+    echo "  --with-cudnn[=directory] $(show_default $(find_cudnn))"
     echo "  --with-hipdnn[=directory] $(show_default $(find_hipdnn))"
     echo "  --with-nccl[=directory] $(show_default $(find_nccl))"
     echo "  --with-mkl[=directory] $(show_default $(find_mkl))"
@@ -741,14 +752,35 @@ do
                 fi
             fi
             ;;
-        --with-hipdnn*)
+        --with-cudnn*)
+            have_cudnn=yes
+            if test x$optarg = x
+            then
+                cudnn_path=$(find_cudnn)
+                if test x$cudnn_path = x
+                then
+                    echo "Cannot find NVIDIA cuDNN directory."
+                    echo "Please specify a value for --with-cudnn"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $cudnn_check) = yes
+                then
+                    cudnn_path=$optarg
+                else
+                    echo "Invalid cuDNN directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+	--with-hipdnn*)
             have_hipdnn=yes
             if test x$optarg = x
             then
                 hipdnn_path=$(find_hipdnn)
                 if test x$hipdnn_path = x
                 then
-                    echo "Cannot find NVIDIA cuDNN directory."
+                    echo "Cannot find hipDNN directory."
                     echo "Please specify a value for --with-hipdnn"
                     exit 1
                 fi
@@ -757,7 +789,7 @@ do
                 then
                     hipdnn_path=$optarg
                 else
-                    echo "Invalid cuDNN directory $optarg"
+                    echo "Invalid hipDNN directory $optarg"
                     exit 1
                 fi
             fi
@@ -1058,14 +1090,25 @@ then
     fi
 fi
 
+if test $enable_cuda = yes && test x$cudnn_path = x
+then
+    cudnn_path=$(find_cudnn)
+    if test x$cudnn_path = x ; then
+        echo Cannot locate NVIDIA cuDNN directory
+        echo CNTK will use default convolution engine.
+    else
+        echo Found cuDNN at $cudnn_path
+    fi
+fi
+
 if test $enable_cuda = yes && test x$hipdnn_path = x
 then
     hipdnn_path=$(find_hipdnn)
     if test x$hipdnn_path = x ; then
-        echo Cannot locate NVIDIA cuDNN directory
+        echo Cannot locate hipDNN directory
         echo CNTK will use default convolution engine.
     else
-        echo Found cuDNN at $hipdnn_path
+        echo Found hipDNN at $hipdnn_path
     fi
 fi
 
@@ -1228,6 +1271,7 @@ if test $enable_cuda = yes || test $enable_hip = yes ; then
     echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
     echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
     echo CUB_PATH=$cub_path >> $config
+    echo CUDNN_PATH=$cudnn_path >> $config
     echo HIPDNN_PATH=$hipdnn_path >> $config
     [ -z "$nccl_path" ] || echo NCCL_PATH=$nccl_path >> $config
 fi
