HIP codes for CNTK-2.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,10 +9,16 @@
 
 configure=$0
 build_top=$PWD
+root_dir=$(dirname "$(readlink -f "$0")")
+external_dir=$root_dir/external/HIP
 
 cuda_path=
 cuda_check=include/cuda.h
 enable_cuda=
+
+hip_path=
+hip_check=include/hip/hip_runtime_api.h
+enable_hip=yes
 
 enable_python=
 
@@ -76,9 +82,17 @@ have_cub=no
 cub_path=
 cub_check=cub/cub.cuh
 
+have_cubhip=no
+cubhip_path=
+cubhip_check=cub/cub.cuh
+
 have_cudnn=no
 cudnn_path=
 cudnn_check=cuda/include/cudnn.h
+
+have_hipdnn=no
+hipdnn_path=
+hipdnn_check=include/hipDNN.h
 
 have_opencv=no
 opencv_path=
@@ -115,7 +129,7 @@ default_use_asgd=yes
 enable_asgd=$default_use_asgd
 
 # List from best to worst choice
-default_path_list="/usr /usr/local /opt /opt/local /lib /usr/lib"
+default_path_list="/usr /usr/local /opt /opt/rocm /opt/local /lib /usr/lib"
 
 # List from best to worst choice
 default_mkls="mklml/$mklml_version"
@@ -124,12 +138,15 @@ default_openblas=""
 default_boost="boost-1.60.0"
 
 default_cudas="cuda-9.0"
+default_hip="hip"
 default_nccls="nccl"
 default_kaldis="kaldi-trunk kaldi-c024e8aa"
 default_gdk_includes="include/nvidia/gdk cuda/include"
 default_gdk_nvml_libs="src/gdk/nvml/lib cuda/lib64/stubs"
 default_cubs="cub-1.7.4"
+default_cubhips="cub-hip"
 default_cudnns="cudnn-7.0"
+default_hipdnn="hipDNN"
 default_opencvs="opencv-3.1.0 opencv-3.0.0"
 default_protobuf="protobuf-3.1.0"
 default_libzips="libzip-1.1.2"
@@ -139,7 +156,7 @@ default_halide="halide"
 
 function default_paths ()
 {
-    echo $build_top $HOME $default_path_list
+    echo $build_top $external_dir $default_path_list $HOME
 }
 
 # $1 is directory
@@ -203,6 +220,11 @@ function find_cuda ()
     find_dir "$default_cudas" "$cuda_check"
 }
 
+function find_hip ()
+{
+    find_dir "$default_hip" "$hip_check"
+}
+
 function find_kaldi ()
 {
     find_dir "$default_kaldis" "$kaldi_check"
@@ -223,9 +245,19 @@ function find_cub ()
     find_dir "$default_cubs" "$cub_check"
 }
 
+function find_cubhip ()
+{
+	find_dir "$default_cubhips" "$cubhip_check"
+}
+
 function find_cudnn ()
 {
     find_dir "$default_cudnns" "$cudnn_check"
+}
+
+function find_hipdnn ()
+{
+    find_dir "$default_hipdnn" "$hipdnn_check"
 }
 
 function find_opencv ()
@@ -270,7 +302,7 @@ function check_version ()
 
 function default_use_cuda ()
 {
-    if test x$(find_cuda) = x || test x$(find_gdk_include) = x || test x$(find_gdk_nvml_lib) = x || test x$(find_cudnn) = x || test x$(find_cub) = x
+    if test x$(find_cuda) = x || test x$(find_gdk_include) = x || test x$(find_gdk_nvml_lib) = x || test x$(find_cudnn) = x
     then
         echo no
     else
@@ -278,6 +310,17 @@ function default_use_cuda ()
     fi
 }
 enable_cuda=$(default_use_cuda)
+
+function default_use_hip ()
+{
+    if test x$(find_hip) = x || test x$(find_hipdnn) = x || test x$(find_cubhip) = x
+    then
+        echo no
+    else
+        echo yes
+    fi
+}
+#enable_hip=$(default_use_hip)
 
 # TODO allow to pick up from path?
 function check_swig ()
@@ -377,16 +420,19 @@ function show_help ()
     echo "  --1bitsgd[=(yes|no)] use 1Bit SGD $(show_default ${default_use_1bitsgd})"
     echo "  --asgd[=(yes|no)] use ASGD powered by Multiverso $(show_default $(default_use_asgd))"
     echo "  --cuda[=(yes|no)] use cuda GPU $(show_default $(default_use_cuda))"
+    echo "  --hip[=(yes|no)] use HIP $(show_default $(default_use_hip))" #MCW
     echo "  --python[=(yes|no)] with Python bindings $(show_default $(default_use_python))"
     echo "  --java[=(yes|no)] with Java bindings $(show_default $(default_use_java))"
     echo "  --with-jdk[=directory] $(show_default $(find_jdk))"
     echo "  --mpi[=(yes|no)] use MPI communication $(show_default ${default_use_mpi})"
     echo "  --gdr[=(yes|no)] use GPUDirect RDMA $(show_default ${default_cuda_gdr})"
     echo "  --with-cuda[=directory] $(show_default $(find_cuda))"
+    echo "  --with-hip[=directory] $(show_default $(find_hip))"
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
     echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
     echo "  --with-cudnn[=directory] $(show_default $(find_cudnn))"
+    echo "  --with-hipdnn[=directory] $(show_default $(find_hipdnn))"
     echo "  --with-nccl[=directory] $(show_default $(find_nccl))"
     echo "  --with-mkl[=directory] $(show_default $(find_mkl))"
     echo "  --with-mkl-sequential[=directory] $(show_default $(find_mkl))"
@@ -422,7 +468,7 @@ do
         *=)   optarg= ;;
         *)    optarg= ;;
     esac
-
+    #echo "optarg is : $optarg"
     case $key in
         -h|--help)
             show_help
@@ -481,6 +527,17 @@ do
                 enable_cuda=$optarg
             else
                 echo "Invalid value for --cuda $optarg"
+                show_help
+                exit
+            fi
+            ;;
+
+	--hip*)
+            if test x$optarg = xyes || test x$optarg = xno
+            then
+                enable_hip=$optarg
+            else
+                echo "Invalid value for --hip $optarg"
                 show_help
                 exit
             fi
@@ -642,8 +699,30 @@ do
             fi
             ;;
 
+        --with-hip*)
+            enable_hip=yes
+            if test x$optarg = x
+            then
+                hip_path=$(find_hip)
+                if test x$hip_path = x
+                then
+                    echo "Cannot find HIP directory."
+                    echo "Please specify a value for --with-hip"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $hip_check) = yes
+                then
+                    hip_path=$optarg
+                else
+                    echo "Invalid hip directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
         --with-cub*)
-            have_cub=yes
+	    have_cub=yes
             if test x$optarg = x
             then
                 cub_path=$(find_cub)
@@ -664,6 +743,36 @@ do
                 fi
             fi
             ;;
+
+	--with-cubhip*)
+	    if $(enable_hip) = no
+	    then
+		echo "CUB-HIP specified without enabling HIP compile."
+		echo "Enabel HIP compile with --hip=yes before specifying CUB-HIP"
+		exit 
+	    fi
+            have_cubhip=yes
+            if test x$optarg = x
+            then
+                cubhip_path=$(find_cub)
+                if test x$cub_path = x
+                then
+                    echo "Cannot find CUB-HIP directory."
+                    echo "Please specify a value for --with-cub"
+                    echo "CUB-HIP can be downloaded from https://github.com/ROCmSoftwarePlatform/cub-hip, extract the archive to /usr/local"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $cubhip_check) = yes
+                then
+                    cubhip_path=$optarg
+                else
+                    echo "Invalid CUB-HIP directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
         --with-gdk-include*)
             have_gdk_include=yes
             if test x$optarg = x
@@ -723,6 +832,33 @@ do
                     cudnn_path=$optarg
                 else
                     echo "Invalid cuDNN directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+	--with-hipdnn*)
+	    if $(enable_hip) = no
+            then
+                echo "CUB-HIP specified without enabling HIP compile."
+                echo "Enabel HIP compile with --hip=yes before specifying CUB-HIP"
+                exit
+            fi
+            have_hipdnn=yes
+            if test x$optarg = x
+            then
+                hipdnn_path=$(find_hipdnn)
+                if test x$hipdnn_path = x
+                then
+                    echo "Cannot find hipDNN directory."
+                    echo "Please specify a value for --with-hipdnn"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $hipdnn_check) = yes
+                then
+                    hipdnn_path=$optarg
+                else
+                    echo "Invalid hipDNN directory $optarg"
                     exit 1
                 fi
             fi
@@ -960,6 +1096,7 @@ if test x$buildtype = x
 then
     buildtype=$default_buildtype
     echo Defaulting to --with-buildtype=release
+    /bin/bash $root_dir/install_hiplibs.sh
 fi
 
 # If no math library was specified, search for mkl
@@ -989,6 +1126,18 @@ then
     fi
 fi
 
+if test x$enable_hip = xyes && test x$hip_path = x
+then
+    hip_path=$(find_hip)
+    if test x$hip_path = x ; then
+        echo Cannot locate a HIP directory
+        echo GPU will be disabled
+        enable_hip=no
+    else
+        echo Found HIP at $hip_path
+    fi
+fi
+
 if test $enable_cuda = yes && test x$gdk_include_path = x
 then
     gdk_include_path=$(find_gdk_include)
@@ -1013,7 +1162,7 @@ then
     fi
 fi
 
-if test $enable_cuda = yes && test x$cub_path = x
+if test $enable_cuda = yes && test x$cub_path = x && test $enable_hip = no
 then
     cub_path=$(find_cub)
     if test x$cub_path = x ; then
@@ -1026,6 +1175,19 @@ then
     fi
 fi
 
+if test $enable_hip = yes && test x$cubhip_path = x
+then
+    cubhip_path=$(find_cubhip)
+    if test x$cubhip_path = x ; then
+        echo Cannot locate CUB-HIP directory
+        echo GPU will be disabled
+        echo CUB-HIP can be downloaded from https://github.com/ROCmSoftwarePlatform/cub-hip, extract the archive to /usr/local 
+        enable_hip=no
+    else
+        echo Found CUB-HIP at $cubhip_path
+    fi
+fi
+
 if test $enable_cuda = yes && test x$cudnn_path = x
 then
     cudnn_path=$(find_cudnn)
@@ -1034,6 +1196,17 @@ then
         echo CNTK will use default convolution engine.
     else
         echo Found cuDNN at $cudnn_path
+    fi
+fi
+
+if test $enable_hip = yes && test x$hipdnn_path = x
+then
+    hipdnn_path=$(find_hipdnn)
+    if test x$hipdnn_path = x ; then
+        echo Cannot locate hipDNN directory
+        echo CNTK will use default convolution engine.
+    else
+        echo Found hipDNN at $hipdnn_path
     fi
 fi
 
@@ -1200,12 +1373,23 @@ if test $cuda_gdr = yes ; then
 else
     echo CUDA_GDR=0 >> $config
 fi
-if test $enable_cuda = yes ; then
-    echo CUDA_PATH=$cuda_path >> $config
-    echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
-    echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
-    echo CUB_PATH=$cub_path >> $config
-    echo CUDNN_PATH=$cudnn_path >> $config
+if test $enable_cuda = yes || test $enable_hip = yes ; then
+    if test $enable_cuda = yes
+    then
+    	echo CUDA_PATH=$cuda_path >> $config
+    	echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
+    	echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
+        echo CUDNN_PATH=$cudnn_path >> $config
+    fi
+    if test $enable_hip = no
+    then
+	echo CUB_PATH=$cub_path >> $config
+    else
+        echo HIP_PATH=$hip_path >> $config
+	echo CUB_PATH=$cubhip_path >> $config
+        echo HIPDNN_PATH=$hipdnn_path >> $config
+        echo EXTERNAL_DIR=$external_dir >> $config
+    fi
     [ -z "$nccl_path" ] || echo NCCL_PATH=$nccl_path >> $config
 fi
 if test $enable_python = yes || test $enable_java = yes ; then
